config/routes.rb
Rails.application.routes.draw do
  root 'accounts#index'
  resources :accounts
end

app/models/account.rb
class Account < ApplicationRecord 
	validates :date, :title, :amount, presence: true

	def self.balance
		where("amount > ?",0 ).sum(:amount)
	end	

	def self.debt
		where("amount < ?",0).sum( :amount)
	end

	def self.total
		sum (:amount)
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
	
	def index
		@accounts = Account.all
		@balance = Account.balance
		@debt = Account.debt
		@total = Account.total
	end

	def create
		@account = Account.create(account_params)
		if @account.valid?
      		flash[:success] = "Your record has been posted!"
    	else
      		flash[:alert] = "Woops! Looks like there has been an error!"
    	end
    		redirect_to root_path
  end
	
	def edit
  		@account = Account.find(params[:id])
	end

	def new
	end

	def update
		@account = Account.find(params[:id])

		if @account.update(account_params)
			flash[:success] = "New Record has been updated!"
			redirect_to root_path
		else
			flash[:alert] = "Woops!Looks like there has been an error!"
		
			redirect_to edit_account_path(params[ :id])
		end
		
	end

	def destroy
		@account = Account.find(params[:id])
		@account.destroy
		flash[:success] = "The record was successfully deleted!"
		redirect_to root_path
	end

	private 

	def account_params
		params.require(:account).permit(:date, :title, :amount)
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/edit.html.erb
<h1>Revise Account</h1>

<%= simple_form_for @account, method: :patch do |f| %>
<%= f.input :date %>
  <%= f.input :title %>
  <%= f.input :amount %>
  <%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/accounts/index.html.erb
<div class="container">
	<h1>Balance :<%= @balance %> </h1>
	<h1>Debt :<%= @debt %> </h1>
	<h1>Total : <%= @total %></h1>
	
	<table class="table">
		<tbody>
			<tr>
				<th>Date</th>
				<th>Title</th>
				<th>Amount</th>
				<th>Edit</th>
				<th>Delete</th>
			</tr>
			<% @accounts.each do |account| %>
			<tr>
				<td><%= account.date %></td>
				<td><%= account.title %></td>
				<td><%= account.amount %></td>
				<td><%= link_to 'Edit', edit_account_path(account), class: 'btn btn-sm btn-success' %></td>
				<td><%= link_to 'Delete', account_path(account), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} %></td>
			</tr>
			<% end %>
		</tbody>	
	</table>
</div>

app/views/accounts/new.html.erb
<%= simple_form_for Account.new do |f| %>
  <%= f.input :date %>
  <%= f.input :title%>
  <%= f.input :amount%>
<%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/ideas/index.html.erb
<%= simple_form_for Account.new do |f| %>
  <%= f.input :date %>
  <%= f.input :title%>
  <%= f.input :amount%>
<%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wallet</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Simple Accounting</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "New Record",new_account_path %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
 <%= render 'shared/flash_messages' %>
    <%= yield %>

  <div class="footer text-center">
    <p>© Salina <%= Date.today.year %> All Rights Reserved</p>    
  </div>

  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "notice" %>
    <p class="alert alert-info alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= notice %></p>
  <% elsif message_type == "alert" %>
    <p class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= alert %></p>
  <% else %>
    <div class="alert alert-<%= message_type %> alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= message %></div>
  <% end %>
<% end %>